### ISSUE TITLE
怎么关闭便携模式

### ISSUE THREAD

**Issue by liuasktao** [ysc3839/ClashXW#1]
开启便携模式后，怎么关闭便携模式？

**Comment by liuasktao** [comment]
Can the configuration file be placed in the program directory in the closed writing mode

**Comment by ysc3839** [comment]
把 exe 所在目录下的 `Data` 目录删除或改名，再启动即可重新选择是否使用便捷模式。

“closed writing mode”指的是什么？

**Comment by liuasktao** [comment]
在非便携模式下，配置文件同样放到程序目录或者放到个人文件夹根目录会不会方便修改配置文件，目前非编写模式的配置文件很难找到位置

**Comment by ysc3839** [comment]
菜单中有打开配置文件目录的选项，不至于很难找到位置吧？

**Comment by liuasktao** [comment]
好的，一直没注意到，个人习惯直接翻目录😅
