### ISSUE TITLE
不能在Windows10 21H1中自适应暗色模式

### ISSUE THREAD

**Issue by ElemenTP** [ysc3839/ClashXW#10]
如题，20H2下自适应暗色模式正常，升级21H1后状态栏图标和菜单只会一直保持亮色模式。  
已尝试过重启电脑、切换颜色模式，无效。
我的两台电脑都有这个问题，应该是21H1做了一些改动。
![屏幕截图 2021-05-20 204046](https://user-images.githubusercontent.com/57991536/118980138-c294a600-b9ab-11eb-9ee9-514ec478e262.jpg)
![屏幕截图 2021-05-20 204103](https://user-images.githubusercontent.com/57991536/118980159-c9231d80-b9ab-11eb-9f17-4866ff8ba467.jpg)

**Comment by ysc3839** [comment]
这是正常情况。
因为暗色模式使用的是未公开的 API，为了避免新版本的系统改动后出现问题，在不支持的系统上是不会启用的。
请等待新版本更新。
