### ISSUE TITLE
ipv6的节点用不了，设置中也找不到能打开ipv6的选项。ipv6节点在cfw中试用通过能用的。不知道能不能加上这个功能。谢谢。

### ISSUE THREAD

**Issue by fyhzc** [ysc3839/ClashXW#13]

**Comment by ysc3839** [comment]
要在配置文件中开启 IPv6 https://github.com/Dreamacro/clash/wiki/configuration#all-configuration-options

ClashX 并没有提供修改配置文件中选项的功能，所以 ClashXW 也会遵循这个设计，需要你手动编辑配置文件开启。
