### ISSUE TITLE
请问后续有增加GUI的打算么？

### ISSUE THREAD

**Issue by lkmvip** [ysc3839/ClashXW#2]
我看了一下现在是用Dashboard来实现设置等功能，那后续会程序上增加GUI吗？

**Comment by ysc3839** [comment]
Dashboard 和菜单就已经是 GUI 了。至于其他界面，该项目会在技术可行的情况下完全模仿 [ClashX](https://github.com/yichengchen/clashX)，所以只有 ClashX 加入了此类界面，本项目才会加入。
