### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xiaoyao2021** [ysc3839/ClashXW#22]
1.clashxw在使用中在取消了“允许来自局域网的连接”后，每次电脑重启后“允许来自局域网的连接”都会自动启用。
2.下载来自“https://raw.githubusercontent.com”的配置文件时显示错误，无法下载，但是其他的软件都能下载。

**Comment by ysc3839** [comment]
1. 允许局域网是由 clash 的配置文件控制的，你需要修改 clash 的配置文件才能保留更改。
2. 目前 HTTP 请求没有走代理，这个问题将在后续的版本修复。
