### ISSUE TITLE
试用了几小时，发现一些问题，以及有一些疑问

### ISSUE THREAD

**Issue by lkmvip** [ysc3839/ClashXW#3]
环境是win10x64
遇到的问题就是，“设置为系统代理”这个选项，打开这个选项后，关闭软件再打开，图标虽然是白色图标，但是实际上并未勾选，任然需要自己手动勾选

另外Config\config.yaml内功能似乎并未被完全实现吗？尝试修改了一下里面的参数，发现没有效果，比如api监听端口，无论怎么改，依旧是9090，还有Dashboard，无论怎么改，打开的还是软件内置的那个，或者说，使用软件的“控制台”打开的，只能是软件内置的那个么？

最后就是关于便携模式，当软件在便携模式下会丢失一些功能，猜测可能是为了避免文件夹权限可能会导致的软件异常？如果只是这样的话，那希望这方面还是做个提醒之类的功能，不要强制关闭一些功能。

**Comment by ysc3839** [comment]
1. 确认是有这个问题，感谢反馈。
2. 监听端口和 Dashboard 路径都通过命令行参数覆盖了，不会使用配置文件中的。因为用户的配置文件可能并不包含这两项设置，不通过命令行设置的话会出现问题。想要修改 Dashboard 的话可以直接修改软件目录下那个。
3. 那些被禁用的功能都是全局、非便捷功能。比如说开机自动启动，是通过判断“启动”文件夹下是否存在 `ClashXW.lnk`，如果便捷模式允许的话就会出现其中一个开启了，其他也显示开启的问题。至于 URL Protocol，当运行多个 ClashXW 的时候，就会遇到“该打开哪一个”的问题，所以也只允许全局模式使用。另外便捷模式也是为了不往软件自身目录以外的地方写东西，所以禁止这些功能也合理。另外在询问是否开启便捷模式时也提到了会禁用这些功能。

**Comment by lkmvip** [comment]
Q1我发现是void EnableSystemProxy(bool enable)里面关于端口设置的问题，应该是程序首次开启时无法正确获取到clash使用的端口，我单纯注释掉enable = false之后发现程序会把端口置为80，我暂时是在这里强制设置为7890，现在能正常使用上了

还是关于配置这段，因为也是通过设置为系统代理，全都转发到clash进行判断，那是否在设置文件内可以加一个列表，如CFW那样的，用于系统代理内设置的直连，具体看下图

![11111](https://user-images.githubusercontent.com/12974141/115118492-f445d600-9fd5-11eb-84fc-0aa8eac16803.png)

**Comment by ysc3839** [comment]
可以加入此功能。

**Comment by lkmvip** [comment]
每次开机，都会提示‘Clash 已启动，但无法通信 点击以查看控制台日志’  然后通知栏里面点击这个又会消失，打不开控制台，而手动开控制台又没发现异常

看了一下代码，可能将这段提示放在catch (...)里面会更好？

**Comment by ysc3839** [comment]
我自己没法复现此问题，开机启动是正常的，手动把 clash.exe 替换成其他非 clash 程序，提示错误时点击通知也能打开控制台。
估计是你电脑性能不好，clash 启动太慢，导致 ClashXW 通信失败。但后面你打开控制台时 clash 已经启动了，所以看不出问题。
至于把提示放在 `catch (...)` 里是不可行的，因为要实现的效果是重试三次都无法通信时才会提示错误。
将会把重试次数改成5次。

**Comment by lkmvip** [comment]
好的，了解

**Comment by ysc3839** [comment]
之前提到的问题、功能，已经在最新的提交中修复、实现了。
