### ISSUE TITLE
请加上能设定混合端口功能。

### ISSUE THREAD

**Issue by fyhzc** [ysc3839/ClashXW#4]
能不能像cfw那样可能设定混合端口啊，谢谢。

**Comment by ysc3839** [comment]
请手动修改配置文件。没记错的话 ClashX 也是同样的设计，不可在控制台中修改。

**Comment by fyhzc** [comment]
请问在那里设置啊，找不到啊，请教一下吧。

**Comment by ysc3839** [comment]
就是改 clash 的配置文件。

**Comment by lkmvip** [comment]
系统托盘ClashXW图标右键，配置-打开配置文件夹，要修改的是你在具体使用的配置文件里面的端口，而不是这个目录下的config.yaml，具体你打开配置文件就知道了。

cfw和ClashXW不一样，cfw是外置了配置信息到config.yaml，而ClashXW是配置和节点等全都在一起。
